name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build --prod

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          branch: gh-pages # Change to your desired GitHub Pages branch name
          folder: website # Change to the folder where your Angular app is built
          token: ${{ secrets.GITHUB_TOKEN }}
